# Generated by Django 2.1 on 2019-11-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ManyToManyField(related_name='channel_users', to='api.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Channel'),
        ),
    ]
